version: '3.8'

services:
  # ✅ PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booksdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # ✅ Auto-run SQL script

  # ✅ Redis Cache
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  # ✅ Zookeeper (Required for Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  # ✅ Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka_broker
    restart: always
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  # ✅ Your Go API
  go-books-api:
    build: .
    container_name: go_books_api
    restart: always
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://postgres:postgres@postgres:5432/booksdb?sslmode=disable"
      REDIS_HOST: "redis:6379"
      KAFKA_BROKER: "kafka:9092"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
